apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webservice-b
  name: webservice-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice-b
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webservice-b
    spec:
      containers:
      - image: 21701jake/web-service-b:latest
        name: webservice-b-api